from typing import Protocol
from uuid import UUID

from api_supplier.domain.entities.supplier import Supplier


class SupplierRepository(Protocol):
    async def add(self, supplier: Supplier) -> None: ...

    async def update(self, supplier: Supplier) -> None: ...

    async def get_by_id(self, supplier_id: UUID) -> Supplier | None: ...

    async def get_all(self) -> list[Supplier]: ...

    async def get_by_tax_id(self, tax_id: str) -> Supplier | None: ...
