from typing import Protocol, Self
from consumer_sap.domain.repositories.repositories import InboxRepository, SapSyncOperationRepository, OutboxRepository

class SapIntegrationUnitOfWork(Protocol):
    inbox: InboxRepository
    operations: SapSyncOperationRepository
    outbox_messages: OutboxRepository
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
