from typing import Protocol, Self
from worker_supplier_outbox.domain.repositories.outbox_repository import OutboxRepository

class OutboxUnitOfWork(Protocol):
    outbox_messages: OutboxRepository
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
