from typing import Protocol
from uuid import UUID
from consumer_sap.domain.entities.sap_sync_operation import SapSyncOperation
from consumer_sap.domain.entities.outbox_message import OutboxMessage

class InboxRepository(Protocol):
    async def exists(self, message_id: UUID) -> bool: ...
    async def add(self, message_id: UUID, event_type: str) -> None: ...

class SapSyncOperationRepository(Protocol):
    async def get_by_message_id(self, message_id: UUID) -> SapSyncOperation | None: ...
    async def add(self, operation: SapSyncOperation) -> None: ...
    async def update(self, operation: SapSyncOperation) -> None: ...

class OutboxRepository(Protocol):
    async def add(self, message: OutboxMessage) -> None: ...
